export enum UserRole {
  GUEST = 'GUEST',
  LEARNER = 'LEARNER',
  SHARER = 'SHARER',
  ADMIN = 'ADMIN'
}

export enum ViewState {
  LANDING = 'LANDING',
  ABOUT = 'ABOUT',
  LOGIN = 'LOGIN',
  REGISTER = 'REGISTER',
  DASHBOARD = 'DASHBOARD',
  MY_COURSES = 'MY_COURSES',
  CREATED_COURSES = 'CREATED_COURSES',
  JOINED_COURSES = 'JOINED_COURSES',
  COURSE_DETAIL = 'COURSE_DETAIL',
  USER_PROFILE = 'USER_PROFILE',
  CREATE_COURSE = 'CREATE_COURSE',

  ANALYTICS = 'ANALYTICS',
  ANALYTICS_PERFORMANCE = 'ANALYTICS_PERFORMANCE',
  ANALYTICS_QUIZ = 'ANALYTICS_QUIZ',
  ANALYTICS_COMMENTS = 'ANALYTICS_COMMENTS',
  ADMIN_USER_MANAGEMENT = 'ADMIN_USER_MANAGEMENT',
  ADMIN_USER_MANAGEMENT_SHARER = 'ADMIN_USER_MANAGEMENT_SHARER',
  ADMIN_USER_MANAGEMENT_UPGRADE = 'ADMIN_USER_MANAGEMENT_UPGRADE',
  ADMIN_USER_MANAGEMENT_CONTROL = 'ADMIN_USER_MANAGEMENT_CONTROL',
  ADMIN_SHARER_REGISTRATION = 'ADMIN_SHARER_REGISTRATION',
  ADMIN_SHARER_REQUESTS = 'ADMIN_SHARER_REQUESTS',
  ADMIN_CONTENT_MANAGEMENT = 'ADMIN_CONTENT_MANAGEMENT',
  ADMIN_PLATFORM_ANALYTICS = 'ADMIN_PLATFORM_ANALYTICS'
}

export interface NavLink {
  label: string;
  href: string;
}